trigger:
- master

pool:
  vmImage: macOS-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- script: |
    echo "Listing contents of the target directory..."
    ls -R $(System.DefaultWorkingDirectory)/target
  displayName: 'Check target directory contents'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    artifactName: 'warfile'
    publishLocation: 'Container'
