trigger:
- master  # Automatically run the pipeline whenever code is pushed to the 'master' branch

pool:
  vmImage: macOS-latest  # Use a macOS build agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml (same level in this case)
    mavenOptions: '-Xmx3072m'  # Memory options for Maven
    javaHomeOption: 'JDKVersion'  # Use a specific JDK version
    jdkVersionOption: '1.11'  # Use Java 11 (matches your setup)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true  # Publish test results to Azure DevOps
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to JUnit test results
    goals: 'clean package'  # Maven goals to clean, compile, and package your app
- task: CopyFiles@2
  inputs:
    Contents: '**/.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
